### PR TITLE
Bring back my changes here

### PR DESCRIPTION
**Pull request by AmauryCarrade**
I'm a little bit late, but anyway, here's the PR. =)

### CODE REVIEW

**Comment by halcy** [comment]
Lovely. Merged. Next up would be you deleting (or renamin?) your fork so I can transfer (I tried it just now, it refuses to transfer while you have a repo of the same name as this one)

**Comment by AmauryCarrade** [comment]
Done :) .

**Comment by halcy** [comment]
Transfer requested! Thank you for stepping up as a maintainer!

**Comment by AmauryCarrade** [comment]
Accepted, and done =)

>Thank you for stepping up as a maintainer!

You're welcome! Of course, you'll keep full access to the repository.

**Comment by MaximeMichaud** [comment]
Thank you !!!!

**Comment by remram44** [comment]
Amazing, open source at work! Thank you guys!

**Pull request merged**
